[package]
name = "weakkey"
version = "0.3.0"
edition = "2024"
readme = "README.md"
license = "MIT"
description = "Weak reference type usable as a key"
keywords = ["Arc", "Rc", "Weak", "no_std"]
repository = "https://github.com/cbbowen/weakkey"

[dev-dependencies]
proptest = "1.9"
